title: Joe Cappadona
author:
  name: Joseph Cappadona
  email: josephcappadona27@gmail.com
description: 

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    github:  josephcappadona
    twitter: seaghost27
    instagram: joecapps27

header_pages:
 - about.md
 - projects.md
 - ideas.md
 - links.md

theme: minima
plugins:
 - jekyll-seo-tag
 - jekyll-jupyter-notebook
