title: Joe Cappadona
author:
  name: Joseph Cappadona
  email: josephcappadona27@gmail.com
description: 

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    github:  josephcappadona
    twitter: joecappadona
    googlescholar: my0vOyQAAAAJ
    # instagram: j.cappadona

header_pages:
  - software.md
  - papers.md
 # - about.md

theme: minima
plugins:
 - jekyll-seo-tag
 - jekyll-jupyter-notebook
